import { useEffect, useRef, useState } from 'react'
import { Activity, ArrowUpRight, Boxes, BrainCircuit, ChevronRight, FileText, FlaskConical, Gauge, Layers3, LockKeyhole, Network, Plus, Search, Settings2, Shield, ShieldAlert, Upload, RefreshCw } from 'lucide-react'
import { request, type Analysis, type Summary, type Finding } from './api/types'
import { Badge, Empty, EvidenceValue, Panel, percent, ScoreCards } from './components/common'
import NewAnalysis from './components/NewAnalysis'

const navigation = [
  ['Overview', Gauge], ['New Analysis', Upload], ['Protocol Analysis', Network],
  ['Security Associations', Layers3], ['Encrypted Traffic AI', BrainCircuit],
  ['Security Assessment', Shield], ['Findings', ShieldAlert], ['Threat Matrix', Boxes],
  ['Reports', FileText], ['Testbed / Demo', FlaskConical], ['System', Settings2],
] as const
type Page = typeof navigation[number][0]
const subtitles: Record<Page,string> = {
  Overview:'Protocol visibility. Evidence-backed decisions.',
  'New Analysis':'Bring your capture. Build an assessment from evidence.',
  'Protocol Analysis':'Visible outer headers and IKE negotiation metadata.',
  'Security Associations':'Directional observations, with configuration provenance.',
  'Encrypted Traffic AI':'Statistical inference from encrypted-flow metadata.',
  'Security Assessment':'Policy decisions with explicit evidence coverage.',
  Findings:'Trace each conclusion back to its supporting evidence.',
  'Threat Matrix':'Review observed signals and unresolved security questions.',
  Reports:'Portable, self-contained assessment reports.',
  'Testbed / Demo':'Reproducible laboratory scenarios. Explicit synthetic provenance.',
  System:'Local service and trusted classifier information.',
}
function FindingList({findings}: {findings: Finding[]}) {
  const [severity,setSeverity]=useState('ALL'), [source,setSource]=useState('ALL'), [query,setQuery]=useState(''), [recommendation,setRecommendation]=useState('ALL')
  const filtered=findings.filter(f=>(severity==='ALL'||f.severity===severity)&&(source==='ALL'||f.source===source)&&(recommendation==='ALL'||f.recommendation===recommendation)&&f.category.toLowerCase().includes(query.toLowerCase()))
  return <><div className="filters"><div className="search"><Search size={16}/><input aria-label="Category filter" placeholder="Filter categories" value={query} onChange={e=>setQuery(e.target.value)}/></div>
    <select aria-label="Severity filter" value={severity} onChange={e=>setSeverity(e.target.value)}>{['ALL','CRITICAL','HIGH','MEDIUM','LOW','INFO'].map(x=><option key={x}>{x}</option>)}</select>
    <select aria-label="Source filter" value={source} onChange={e=>setSource(e.target.value)}>{['ALL','OBSERVED','DERIVED','ASSISTED','INFERRED','UNKNOWN'].map(x=><option key={x}>{x}</option>)}</select>
    <select aria-label="Recommendation filter" value={recommendation} onChange={e=>setRecommendation(e.target.value)}>{['ALL','ACCEPT','REVIEW','HARDEN','QUARANTINE'].map(x=><option key={x}>{x}</option>)}</select></div>
    {filtered.length===0 ? <Empty>No findings match these filters. This is not a safety conclusion.</Empty> : filtered.map(f=><article className="finding" key={f.finding_id}><div className="finding-top"><Badge>{f.severity}</Badge><h3>{f.category.replaceAll('_',' ')}</h3><Badge>{f.source}</Badge><span className="muted">{percent(f.confidence)} evidence confidence</span></div><p>{f.reason}</p><details><summary>Evidence & remediation <ChevronRight size={14}/></summary><ul>{f.evidence.map((e,i)=><li key={i}><code>{e}</code></li>)}</ul><p><Badge>{f.recommendation}</Badge> {f.remediation}</p>{f.limitations.map((l,i)=><p className="muted" key={i}>{l}</p>)}</details></article>)}</>
}
function Overview({run,go}: {run:Analysis;go:(p:Page)=>void}) {
  const c=run.protocol_observations.counts
  const scores=run.score
  return <><ScoreCards score={scores}/><div className="overview-grid"><Panel title="Evidence coverage" extra={<Badge>{scores.score_status}</Badge>}>
    <div className="coverage-visual"><div className="ring" style={{background:`conic-gradient(var(--teal) ${scores.assessment_coverage*360}deg, #243241 0deg)`}}><div><strong>{percent(scores.assessment_coverage)}</strong><small>ASSESSED</small></div></div><div><h3>{scores.assessment_coverage<1?'An incomplete picture':'Evidence available for each domain'}</h3><p className="muted">Unknown checks receive no secure credit. Coverage measures availability, not authenticity or certification.</p><button className="text-button" onClick={()=>go('Security Assessment')}>Explore assessment <ArrowUpRight size={15}/></button></div></div>
    <div className="domain-mini">{scores.domains.map(d=><div key={d.name}><span>{d.name}</span><div className="bar"><i style={{width:percent(d.coverage)}}/></div><small>{percent(d.coverage)}</small></div>)}</div>
  </Panel><Panel title="Capture at a glance" extra={<Badge>OBSERVED</Badge>}><div className="capture-stats">
    {[['Packets',run.packet_count],['ESP packets',c.ESP??0],['IKE versions',[...new Set(run.protocol_observations.ike_messages.map(m=>m.version))].join(', ')||'UNKNOWN'],['Directional SAs',run.security_associations.length],['AI flows',run.traffic_predictions.length],['Duration',run.capture_duration.toFixed(2)+' s']].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div><div className="notice compact">SPI groupings are observations, not proof of established endpoint SAs.</div></Panel></div>
    <div className="overview-grid"><Panel title="Priority findings" extra={<button className="text-button" onClick={()=>go('Findings')}>View all <ArrowUpRight size={15}/></button>}>
      {[...run.findings].sort((a,b)=>['CRITICAL','HIGH','MEDIUM','LOW','INFO'].indexOf(a.severity)-['CRITICAL','HIGH','MEDIUM','LOW','INFO'].indexOf(b.severity)).slice(0,4).map(f=><div className="priority" key={f.finding_id}><Badge>{f.severity}</Badge><div><strong>{f.category.replaceAll('_',' ')}</strong><p>{f.reason}</p></div></div>)}
      {!run.findings.length&&<Empty>No findings does not mean safe.</Empty>}</Panel>
      <Panel title="Encrypted traffic inference" extra={<Badge>INFERRED</Badge>}>{run.traffic_predictions.slice(0,3).map(p=><div className="prediction-mini" key={p.flow_id}><BrainCircuit size={20}/><div><strong>{p.predicted_class}</strong><small>{p.flow_id}</small></div><strong>{percent(p.confidence)}</strong></div>)}<p className="muted">Synthetic-trained model confidence. No payload was decrypted. Real-world accuracy has not been established.</p></Panel></div>
  </>
}
function Protocol({run}: {run:Analysis}) {
 const p=run.protocol_observations
 return <><div className="notice">Visible IKE transforms are IKE SA proposals, not automatically ESP Child-SA transforms. Encrypted IKE_AUTH / CREATE_CHILD_SA payloads remain opaque.</div><Panel title="Protocol observations" extra={<Badge>OBSERVED</Badge>}><div className="protocol-chips">{Object.entries(p.counts).map(([k,v])=><div key={k}><Activity size={17}/><strong>{k}</strong><span>{v} packets</span></div>)}</div><p className="muted">Malformed: {p.malformed_packets} · Unsupported: {p.unsupported_packets} · Additional endpoint SPI groups: {p.spi_changes} (possible SA changes, not proven rekeys) · AH next headers: {p.ah_next_headers.join(', ')||'not observed'}</p></Panel>
 <Panel title="IKE messages & visible proposals">{p.ike_messages.length===0?<Empty>IKE not observed. Child-SA crypto remains UNKNOWN without telemetry.</Empty>:p.ike_messages.map((m,i)=><details className="ike-message" key={i} open={i===0}><summary><Badge>{m.version}</Badge><strong>{m.exchange}</strong><code>{m.src} → {m.dst}</code><Badge>{m.source}</Badge></summary><p>Initiator SPI <code>{m.initiator_spi}</code> · Responder SPI <code>{m.responder_spi}</code> · KE group {m.ke_group??'UNKNOWN'} · Encrypted payload {String(m.encrypted)}</p><div className="table-wrap"><table><thead><tr><th>Proposal</th><th>Type / ID</th><th>Algorithm</th><th>Key bits</th><th>Scope</th></tr></thead><tbody>{m.transforms.map((t,j)=><tr key={j}><td>{t.proposal} / protocol {t.protocol_id}</td><td>{t.transform_type} / {t.transform_id}</td><td>{t.name}</td><td>{t.key_length??'UNKNOWN'}</td><td>{t.scope}</td></tr>)}</tbody></table></div></details>)}</Panel></>
}
function Associations({run}: {run:Analysis}) {
 return <><div className="notice">Mode, ESP algorithms, PFS, configured lifetime and replay window require matching ASSISTED endpoint evidence. Observed duration is not configured lifetime.</div><Panel title="Directional security associations"><div className="table-wrap"><table><thead><tr><th>SPI / protocol</th><th>Endpoints</th><th>Packets / sequence</th><th>Mode</th><th>Encryption</th><th>PFS</th><th>Lifetime (s)</th><th>Replay window</th></tr></thead><tbody>{run.security_associations.map(sa=><tr key={sa.sa_id}><td><code>{sa.spi}</code><small>{sa.protocol} · IPv{sa.ip_version}{sa.nat_t?' · NAT-T':''}</small></td><td><code>{sa.source}<br/>↓ {sa.destination}</code></td><td>{sa.packet_count}<small>{sa.sequence_min}–{sa.sequence_max}</small></td><td><EvidenceValue value={sa.mode}/></td><td><EvidenceValue value={sa.encryption_algorithm}/><EvidenceValue value={sa.encryption_key_bits}/></td><td><EvidenceValue value={sa.pfs_enabled}/></td><td><EvidenceValue value={sa.configured_lifetime}/></td><td><EvidenceValue value={sa.replay_window}/></td></tr>)}</tbody></table></div>{!run.security_associations.length&&<Empty/>}</Panel>
 {run.security_associations.map(sa=><Panel title={sa.spi+' · sequence signals & configuration'} key={sa.sa_id}><div className="signal-grid">{Object.entries(sa.replay_signals).map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><strong>{v}</strong></div>)}<div><span>Observed duration</span><strong>{sa.observed_duration.toFixed(2)} s</strong></div></div><div className="signal-grid"><div><span>Integrity</span><EvidenceValue value={sa.integrity_algorithm}/></div><div><span>DH group</span><EvidenceValue value={sa.dh_group}/></div><div><span>ESN</span><EvidenceValue value={sa.esn}/></div></div><p className="muted">Sequence anomalies do not prove replay attacks or endpoint acceptance. Gaps can reflect packet loss; regressions can reflect reordering or ESN wrap.</p></Panel>)}</>
}
function Traffic({run}: {run:Analysis}) {return <><div className="notice prominent"><LockKeyhole size={20}/><div><strong>Encrypted payload was not decrypted. Classification is based on flow metadata.</strong><p>Model trained on synthetic profiles. AI confidence is not attack probability or real-world accuracy.</p></div></div>{run.traffic_predictions.map(p=><Panel title={p.flow_id} key={p.flow_id} extra={<Badge>INFERRED</Badge>}><div className="traffic-heading"><h3>{p.predicted_class}</h3><strong>{percent(p.confidence)} confidence</strong><span>{p.features.packet_count} sampled packets · {p.features.duration.toFixed(2)} s</span></div><div className="probabilities">{Object.entries(p.probabilities).map(([label,value])=><div key={label}><span>{label}</span><div className="bar"><i style={{width:percent(value)}}/></div><strong>{percent(value)}</strong></div>)}</div><details><summary>Feature summary & limitations</summary><div className="feature-grid">{Object.entries(p.features).map(([k,v])=><div key={k}><small>{k}</small><code>{v.toFixed(3)}</code></div>)}</div>{p.limitations.map(l=><p className="muted" key={l}>{l}</p>)}</details></Panel>)}{!run.traffic_predictions.length&&<Empty>No eligible ESP flows.</Empty>}</>}
function Assessment({run}: {run:Analysis}) {return <><ScoreCards score={run.score}/><Panel title="Domain assessment" extra={<Badge>{run.policy}</Badge>}>{run.score.domains.map(d=><div className="domain-row" key={d.name}><div><h3>{d.name}</h3><span className="muted">Weight {percent(d.weight)} · Coverage {percent(d.coverage)}</span></div><div className="bar"><i style={{width:(d.score??0)+'%'}}/></div><strong>{d.score===null?'UNKNOWN':d.score.toFixed(1)}</strong><details><summary>Evidence</summary>{d.evidence.map((e,i)=><p key={i}><code>{e}</code></p>)}</details></div>)}</Panel><div className="notice">Overall score averages known checks weighted by domain weight and coverage. Below 50% coverage, the score is unavailable. HIGH findings require HARDEN regardless of score. A high score does not verify unseen configuration.</div></>}
function Reports({run}: {run:Analysis}) {
 const [snippet,setSnippet]=useState(''),[error,setError]=useState('')
 useEffect(()=>{const abort=new AbortController(); setSnippet(''); setError(''); request<{snippet:string}>('/analyses/'+run.analysis_id+'/hardening',{signal:abort.signal}).then(r=>setSnippet(r.snippet)).catch(e=>{if(!abort.signal.aborted)setError(String(e))});return()=>abort.abort()},[run.analysis_id])
 return <><div className="report-grid">{['executive','technical'].map(kind=><Panel title={kind==='executive'?'Executive report':'Technical report'} key={kind} extra={<FileText/>}><p className="muted">{kind==='executive'?'Decision summary, score, coverage, risks and recommendations.':'Protocol details, SA evidence, classifier probabilities, threat matrix and domain scoring.'}</p><a className="button primary" href={'/api/analyses/'+run.analysis_id+'/report/'+kind} download>Download {kind} HTML <ArrowUpRight size={16}/></a></Panel>)}</div><Panel title="Configuration hardener" extra={<Badge>RECOMMENDATION</Badge>}><p>Review these policy-specific improvements before manual use. No host VPN configuration is modified.</p>{error&&<p role="alert">{error}</p>}<pre>{snippet||'Loading recommendation…'}</pre></Panel><Panel title="Assessment limitations"><ul className="limitations">{run.limitations.map(l=><li key={l}>{l}</li>)}</ul></Panel></>
}
function Testbed() {
 return <><div className="notice">SYNTHETIC FIXTURE demos are available after <code>make demo</code>. Testbed live status: NOT MONITORED. Generated fixtures are not real VPN captures.</div><div className="demo-grid">{[['strong','Modern / strong','IKEv2, AES-256-GCM, ECP384; matching synthetic telemetry.'],['weak','Legacy / weak','CBC/SHA1, DH2, PFS disabled, long lifetime, sequence anomalies.'],['replay','Replay signals','Duplicate and regressing sequences. Endpoint acceptance unknown.'],['partial','Partial evidence','ESP only. Mode, crypto, PFS and replay window remain UNKNOWN.'],['ipv6','IPv6 + AH','IPv6, NAT-T ESP, visible IKE and a basic AH header.']].map(([id,title,desc])=><Panel key={id} title={title} extra={<Badge>SYNTHETIC FIXTURE</Badge>}><p className="muted">{desc}</p><code>demo/{id}/{id}.pcap</code><p className="muted">{['strong','weak','ipv6'].includes(id)?'Import telemetry.json from the same directory.':'No telemetry: expect UNKNOWN fields.'}</p></Panel>)}</div><Panel title="Local commands"><pre>{'make demo\nmake backend\nmake frontend\n\n# Optional isolated lab configuration generation\n.venv/bin/python -m testbed.scripts.generate --profile modern --mode tunnel\n# See testbed/README.md before starting containers.'}</pre><p className="muted">Configuration generator supports CBC/GCM, 128/256-bit AES, DH14/19/31, PFS on/off, tunnel/transport, IPv4/IPv6. Live interoperability must be verified on the host.</p></Panel></>
}
function System() {
 const [data,setData]=useState<unknown>(null),[error,setError]=useState('')
 useEffect(()=>{const a=new AbortController();request('/model/info',{signal:a.signal}).then(setData).catch(e=>{if(!a.signal.aborted)setError(String(e))});return()=>a.abort()},[])
 return <Panel title="Trusted local classifier">{error&&<p role="alert">{error}</p>}<p className="muted">Runtime has no external cloud dependency. Model is read from a fixed built-in JSON artifact with a SHA-256 check. User model uploads are not accepted.</p><pre>{data?JSON.stringify(data,null,2):'Loading model information…'}</pre></Panel>
}
export default function App() {
 const [page,setPage]=useState<Page>('Overview'),[history,setHistory]=useState<Summary[]>([]),[id,setId]=useState(''),[run,setRun]=useState<Analysis|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false),[health,setHealth]=useState('CONNECTING')
 const ticket=useRef(0)
 async function refresh() {try {setHistory(await request<Summary[]>('/analyses'))}catch(e){setError(e instanceof Error?e.message:'Unable to load analyses')}}
 useEffect(()=>{const a=new AbortController();request<Summary[]>('/analyses',{signal:a.signal}).then(rows=>{setHistory(rows);if(rows[0])setId(rows[0].analysis_id)}).catch(e=>{if(!a.signal.aborted)setError(String(e))});request('/health',{signal:a.signal}).then(()=>setHealth('CONNECTED')).catch(()=>{if(!a.signal.aborted)setHealth('OFFLINE')});return()=>a.abort()},[])
 useEffect(()=>{if(!id){++ticket.current;setRun(null);setLoading(false);return}const a=new AbortController(), current=++ticket.current;setRun(null);setLoading(true);setError('');request<Analysis>('/analyses/'+id,{signal:a.signal}).then(value=>{if(current===ticket.current&&!a.signal.aborted)setRun(value)}).catch(e=>{if(!a.signal.aborted)setError(String(e))}).finally(()=>{if(current===ticket.current&&!a.signal.aborted)setLoading(false)});return()=>a.abort()},[id])
 function completed(value:Analysis) {++ticket.current;setRun(value);setId(value.analysis_id);setPage('Overview');void refresh()}
 function content() {
  if(page==='New Analysis')return <NewAnalysis onComplete={completed}/>
  if(page==='Testbed / Demo')return <Testbed/>
  if(page==='System')return <System/>
  if(loading)return <Empty>Loading selected analysis…</Empty>
  if(!run)return <Empty><Shield size={44}/><h2>Your evidence workspace is ready</h2><p>Upload a capture or run make demo to begin. No assessment has been inferred.</p><button className="primary" onClick={()=>setPage('New Analysis')}>Create analysis <Plus size={16}/></button></Empty>
  if(page==='Overview')return <Overview run={run} go={setPage}/>
  if(page==='Protocol Analysis')return <Protocol run={run}/>
  if(page==='Security Associations')return <Associations run={run}/>
  if(page==='Encrypted Traffic AI')return <Traffic run={run}/>
  if(page==='Security Assessment')return <Assessment run={run}/>
  if(page==='Findings')return <Panel title={'Findings · '+run.findings.length}><FindingList findings={run.findings}/></Panel>
  if(page==='Threat Matrix')return <Panel title="Threat matrix"><div className="table-wrap"><table><thead><tr><th>Threat</th><th>Status / severity</th><th>Confidence</th><th>Evidence & impact</th><th>Recommendation</th></tr></thead><tbody>{run.threat_matrix.map((r,i)=><tr key={i}><td>{r.threat.replaceAll('_',' ')}</td><td><Badge>{r.status}</Badge><Badge>{r.severity}</Badge></td><td>{percent(r.confidence)}</td><td>{r.impact}<details><summary>Evidence</summary>{r.evidence.map((e,j)=><p key={j}><code>{e}</code></p>)}</details></td><td>{r.recommendation}</td></tr>)}</tbody></table></div></Panel>
  return <Reports run={run}/>
 }
 return <div className="app-shell"><aside><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('Overview')}}><div className="brand-icon"><Shield size={24}/></div><span>IPsecLens <b>AI</b><small>PROTOCOL INTELLIGENCE</small></span></a><div className="workspace-label">ANALYST WORKSPACE</div><nav>{navigation.map(([name,Icon])=><button className={page===name?'active':''} key={name} onClick={()=>setPage(name)}><Icon size={18}/><span>{name}</span>{name==='Findings'&&run&&<em>{run.findings.length}</em>}</button>)}</nav><div className="sidebar-footer"><LockKeyhole size={16}/><div><strong>Local evidence. Local control.</strong><small>SIH 26160 · NTRO prototype</small></div></div></aside><div className="main"><header className="topbar"><div className="breadcrumb">Workspace <ChevronRight size={14}/> <span>{page}</span></div><span className="connection"><i className={health.toLowerCase()}/>{health}</span><span className="local-tag">LOCAL / OFFLINE CAPABLE</span></header><main><div className="page-heading"><div><div className="eyebrow">IPSEC SECURITY ASSESSMENT</div><h1>{page}</h1><p>{subtitles[page]}</p></div><button className="primary" onClick={()=>setPage('New Analysis')}><Plus size={17}/>New analysis</button></div>
 <div className="analysis-strip"><div><Layers3 size={18}/><select aria-label="Selected analysis" value={id} onChange={e=>setId(e.target.value)}><option value="">Select analysis</option>{history.map(h=><option key={h.analysis_id} value={h.analysis_id}>{h.label||h.capture_filename}</option>)}</select><button className="icon-button" aria-label="Refresh analyses" onClick={()=>void refresh()}><RefreshCw size={15}/></button></div>{run&&<div><Badge>{run.policy}</Badge><Badge>{run.analysis_status}</Badge><span className="muted">{run.capture_sha256.slice(0,12)}…</span></div>}</div>
 {error&&<div role="alert" className="error">{error}</div>}{content()}<footer>IPsecLens AI <span>UNKNOWN ≠ SECURE · NO FINDING ≠ SAFE · AI CONFIDENCE ≠ ATTACK PROBABILITY</span></footer></main></div></div>
}
